//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2022 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "github.com/rook/rook/pkg/apis/ceph.rook.io/v1"
	corev1 "k8s.io/api/core/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BlockStorageStatus) DeepCopyInto(out *BlockStorageStatus) {
	*out = *in
	if in.PoolsStatus != nil {
		in, out := &in.PoolsStatus, &out.PoolsStatus
		*out = make(map[string]MiraPoolStatus, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.CephClientsStatus != nil {
		in, out := &in.CephClientsStatus, &out.CephClientsStatus
		*out = make(map[string]MiraCephClientStatus, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BlockStorageStatus.
func (in *BlockStorageStatus) DeepCopy() *BlockStorageStatus {
	if in == nil {
		return nil
	}
	out := new(BlockStorageStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CephDaemonsStatus) DeepCopyInto(out *CephDaemonsStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CephDaemonsStatus.
func (in *CephDaemonsStatus) DeepCopy() *CephDaemonsStatus {
	if in == nil {
		return nil
	}
	out := new(CephDaemonsStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CephDetails) DeepCopyInto(out *CephDetails) {
	*out = *in
	in.UsageDetails.DeepCopyInto(&out.UsageDetails)
	in.DiskUsageDetails.DeepCopyInto(&out.DiskUsageDetails)
	if in.DeviceMapping != nil {
		in, out := &in.DeviceMapping, &out.DeviceMapping
		*out = make(map[string]DeviceMapping, len(*in))
		for key, val := range *in {
			var outVal map[string]OsdDetails
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = make(DeviceMapping, len(*in))
				for key, val := range *in {
					(*out)[key] = val
				}
			}
			(*out)[key] = outVal
		}
	}
	if in.CephDeviceMapping != nil {
		in, out := &in.CephDeviceMapping, &out.CephDeviceMapping
		*out = make(map[string]OsdDeviceMapping, len(*in))
		for key, val := range *in {
			var outVal map[string]string
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = make(OsdDeviceMapping, len(*in))
				for key, val := range *in {
					(*out)[key] = val
				}
			}
			(*out)[key] = outVal
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CephDetails.
func (in *CephDetails) DeepCopy() *CephDetails {
	if in == nil {
		return nil
	}
	out := new(CephDetails)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CephOsdRemoveRequest) DeepCopyInto(out *CephOsdRemoveRequest) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	if in.Spec != nil {
		in, out := &in.Spec, &out.Spec
		*out = new(CephOsdRemoveRequestSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(CephOsdRemoveRequestStatus)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CephOsdRemoveRequest.
func (in *CephOsdRemoveRequest) DeepCopy() *CephOsdRemoveRequest {
	if in == nil {
		return nil
	}
	out := new(CephOsdRemoveRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CephOsdRemoveRequest) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CephOsdRemoveRequestCondition) DeepCopyInto(out *CephOsdRemoveRequestCondition) {
	*out = *in
	if in.Nodes != nil {
		in, out := &in.Nodes, &out.Nodes
		*out = make(map[string]NodeCleanUpSpec, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.MiraCephVersion != nil {
		in, out := &in.MiraCephVersion, &out.MiraCephVersion
		*out = new(MiraCephSpecVersion)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CephOsdRemoveRequestCondition.
func (in *CephOsdRemoveRequestCondition) DeepCopy() *CephOsdRemoveRequestCondition {
	if in == nil {
		return nil
	}
	out := new(CephOsdRemoveRequestCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CephOsdRemoveRequestList) DeepCopyInto(out *CephOsdRemoveRequestList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CephOsdRemoveRequest, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CephOsdRemoveRequestList.
func (in *CephOsdRemoveRequestList) DeepCopy() *CephOsdRemoveRequestList {
	if in == nil {
		return nil
	}
	out := new(CephOsdRemoveRequestList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CephOsdRemoveRequestList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CephOsdRemoveRequestSpec) DeepCopyInto(out *CephOsdRemoveRequestSpec) {
	*out = *in
	if in.Nodes != nil {
		in, out := &in.Nodes, &out.Nodes
		*out = make(map[string]NodeCleanUpSpec, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CephOsdRemoveRequestSpec.
func (in *CephOsdRemoveRequestSpec) DeepCopy() *CephOsdRemoveRequestSpec {
	if in == nil {
		return nil
	}
	out := new(CephOsdRemoveRequestSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CephOsdRemoveRequestStatus) DeepCopyInto(out *CephOsdRemoveRequestStatus) {
	*out = *in
	if in.RemoveInfo != nil {
		in, out := &in.RemoveInfo, &out.RemoveInfo
		*out = new(RequestRemoveInfo)
		(*in).DeepCopyInto(*out)
	}
	if in.Messages != nil {
		in, out := &in.Messages, &out.Messages
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]CephOsdRemoveRequestCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CephOsdRemoveRequestStatus.
func (in *CephOsdRemoveRequestStatus) DeepCopy() *CephOsdRemoveRequestStatus {
	if in == nil {
		return nil
	}
	out := new(CephOsdRemoveRequestStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CephPerfTestCronHistory) DeepCopyInto(out *CephPerfTestCronHistory) {
	*out = *in
	if in.Messages != nil {
		in, out := &in.Messages, &out.Messages
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CephPerfTestCronHistory.
func (in *CephPerfTestCronHistory) DeepCopy() *CephPerfTestCronHistory {
	if in == nil {
		return nil
	}
	out := new(CephPerfTestCronHistory)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CephPerfTestPeriodicParams) DeepCopyInto(out *CephPerfTestPeriodicParams) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CephPerfTestPeriodicParams.
func (in *CephPerfTestPeriodicParams) DeepCopy() *CephPerfTestPeriodicParams {
	if in == nil {
		return nil
	}
	out := new(CephPerfTestPeriodicParams)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CephPerfTestRequest) DeepCopyInto(out *CephPerfTestRequest) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(CephPerfTestRequestStatus)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CephPerfTestRequest.
func (in *CephPerfTestRequest) DeepCopy() *CephPerfTestRequest {
	if in == nil {
		return nil
	}
	out := new(CephPerfTestRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CephPerfTestRequest) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CephPerfTestRequestList) DeepCopyInto(out *CephPerfTestRequestList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CephPerfTestRequest, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CephPerfTestRequestList.
func (in *CephPerfTestRequestList) DeepCopy() *CephPerfTestRequestList {
	if in == nil {
		return nil
	}
	out := new(CephPerfTestRequestList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CephPerfTestRequestList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CephPerfTestRequestSpec) DeepCopyInto(out *CephPerfTestRequestSpec) {
	*out = *in
	if in.Parameters != nil {
		in, out := &in.Parameters, &out.Parameters
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Command != nil {
		in, out := &in.Command, &out.Command
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Periodic != nil {
		in, out := &in.Periodic, &out.Periodic
		*out = new(CephPerfTestPeriodicParams)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CephPerfTestRequestSpec.
func (in *CephPerfTestRequestSpec) DeepCopy() *CephPerfTestRequestSpec {
	if in == nil {
		return nil
	}
	out := new(CephPerfTestRequestSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CephPerfTestRequestStatus) DeepCopyInto(out *CephPerfTestRequestStatus) {
	*out = *in
	if in.Messages != nil {
		in, out := &in.Messages, &out.Messages
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Results != nil {
		in, out := &in.Results, &out.Results
		*out = new(CephPerfTestResults)
		(*in).DeepCopyInto(*out)
	}
	if in.StatusHistory != nil {
		in, out := &in.StatusHistory, &out.StatusHistory
		*out = make([]CephPerfTestCronHistory, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CephPerfTestRequestStatus.
func (in *CephPerfTestRequestStatus) DeepCopy() *CephPerfTestRequestStatus {
	if in == nil {
		return nil
	}
	out := new(CephPerfTestRequestStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CephPerfTestResults) DeepCopyInto(out *CephPerfTestResults) {
	*out = *in
	if in.StoredOnPvc != nil {
		in, out := &in.StoredOnPvc, &out.StoredOnPvc
		*out = new(PvcStoredResults)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CephPerfTestResults.
func (in *CephPerfTestResults) DeepCopy() *CephPerfTestResults {
	if in == nil {
		return nil
	}
	out := new(CephPerfTestResults)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClassDiskUsageStats) DeepCopyInto(out *ClassDiskUsageStats) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClassDiskUsageStats.
func (in *ClassDiskUsageStats) DeepCopy() *ClassDiskUsageStats {
	if in == nil {
		return nil
	}
	out := new(ClassDiskUsageStats)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClassUsageStats) DeepCopyInto(out *ClassUsageStats) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClassUsageStats.
func (in *ClassUsageStats) DeepCopy() *ClassUsageStats {
	if in == nil {
		return nil
	}
	out := new(ClassUsageStats)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeviceCleanUpSpec) DeepCopyInto(out *DeviceCleanUpSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeviceCleanUpSpec.
func (in *DeviceCleanUpSpec) DeepCopy() *DeviceCleanUpSpec {
	if in == nil {
		return nil
	}
	out := new(DeviceCleanUpSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeviceInfo) DeepCopyInto(out *DeviceInfo) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeviceInfo.
func (in *DeviceInfo) DeepCopy() *DeviceInfo {
	if in == nil {
		return nil
	}
	out := new(DeviceInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in DeviceMapping) DeepCopyInto(out *DeviceMapping) {
	{
		in := &in
		*out = make(DeviceMapping, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
		return
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeviceMapping.
func (in DeviceMapping) DeepCopy() DeviceMapping {
	if in == nil {
		return nil
	}
	out := new(DeviceMapping)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiskUsageDetails) DeepCopyInto(out *DiskUsageDetails) {
	*out = *in
	if in.ClassesDetail != nil {
		in, out := &in.ClassesDetail, &out.ClassesDetail
		*out = make(map[string]ClassDiskUsageStats, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.PoolsDetail != nil {
		in, out := &in.PoolsDetail, &out.PoolsDetail
		*out = make(map[string]PoolDiskUsageStats, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiskUsageDetails.
func (in *DiskUsageDetails) DeepCopy() *DiskUsageDetails {
	if in == nil {
		return nil
	}
	out := new(DiskUsageDetails)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostMapping) DeepCopyInto(out *HostMapping) {
	*out = *in
	if in.OsdMapping != nil {
		in, out := &in.OsdMapping, &out.OsdMapping
		*out = make(map[string]OsdMapping, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.HostRemoveStatus != nil {
		in, out := &in.HostRemoveStatus, &out.HostRemoveStatus
		*out = new(RemoveStatus)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostMapping.
func (in *HostMapping) DeepCopy() *HostMapping {
	if in == nil {
		return nil
	}
	out := new(HostMapping)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Mgr) DeepCopyInto(out *Mgr) {
	*out = *in
	if in.Modules != nil {
		in, out := &in.Modules, &out.Modules
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Mgr.
func (in *Mgr) DeepCopy() *Mgr {
	if in == nil {
		return nil
	}
	out := new(Mgr)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MiraCeph) DeepCopyInto(out *MiraCeph) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MiraCeph.
func (in *MiraCeph) DeepCopy() *MiraCeph {
	if in == nil {
		return nil
	}
	out := new(MiraCeph)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MiraCeph) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MiraCephClient) DeepCopyInto(out *MiraCephClient) {
	*out = *in
	in.ClientSpec.DeepCopyInto(&out.ClientSpec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MiraCephClient.
func (in *MiraCephClient) DeepCopy() *MiraCephClient {
	if in == nil {
		return nil
	}
	out := new(MiraCephClient)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MiraCephClientStatus) DeepCopyInto(out *MiraCephClientStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MiraCephClientStatus.
func (in *MiraCephClientStatus) DeepCopy() *MiraCephClientStatus {
	if in == nil {
		return nil
	}
	out := new(MiraCephClientStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MiraCephClusterStatus) DeepCopyInto(out *MiraCephClusterStatus) {
	*out = *in
	in.CephClusterStatus.DeepCopyInto(&out.CephClusterStatus)
	if in.CephDaemonsStatus != nil {
		in, out := &in.CephDaemonsStatus, &out.CephDaemonsStatus
		*out = make(map[string]CephDaemonsStatus, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	in.BlockStorageStatus.DeepCopyInto(&out.BlockStorageStatus)
	if in.ObjectStorageStatus != nil {
		in, out := &in.ObjectStorageStatus, &out.ObjectStorageStatus
		*out = new(ObjectStorageStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.SharedFilesystemStatus != nil {
		in, out := &in.SharedFilesystemStatus, &out.SharedFilesystemStatus
		*out = new(SharedFilesystemStatus)
		(*in).DeepCopyInto(*out)
	}
	in.CephDetails.DeepCopyInto(&out.CephDetails)
	if in.CephCSIPluginDaemonsStatus != nil {
		in, out := &in.CephCSIPluginDaemonsStatus, &out.CephCSIPluginDaemonsStatus
		*out = make(map[string]CephDaemonsStatus, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MiraCephClusterStatus.
func (in *MiraCephClusterStatus) DeepCopy() *MiraCephClusterStatus {
	if in == nil {
		return nil
	}
	out := new(MiraCephClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MiraCephExternalClusterSpec) DeepCopyInto(out *MiraCephExternalClusterSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MiraCephExternalClusterSpec.
func (in *MiraCephExternalClusterSpec) DeepCopy() *MiraCephExternalClusterSpec {
	if in == nil {
		return nil
	}
	out := new(MiraCephExternalClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MiraCephFS) DeepCopyInto(out *MiraCephFS) {
	*out = *in
	in.MetadataPool.DeepCopyInto(&out.MetadataPool)
	if in.DataPools != nil {
		in, out := &in.DataPools, &out.DataPools
		*out = make([]MiraCephFsPool, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.MetadataServer.DeepCopyInto(&out.MetadataServer)
	if in.DataPool != nil {
		in, out := &in.DataPool, &out.DataPool
		*out = new(MiraCephPoolSpec)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MiraCephFS.
func (in *MiraCephFS) DeepCopy() *MiraCephFS {
	if in == nil {
		return nil
	}
	out := new(MiraCephFS)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MiraCephFsPool) DeepCopyInto(out *MiraCephFsPool) {
	*out = *in
	in.MiraCephPoolSpec.DeepCopyInto(&out.MiraCephPoolSpec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MiraCephFsPool.
func (in *MiraCephFsPool) DeepCopy() *MiraCephFsPool {
	if in == nil {
		return nil
	}
	out := new(MiraCephFsPool)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MiraCephFsStatus) DeepCopyInto(out *MiraCephFsStatus) {
	*out = *in
	if in.ActiveClients != nil {
		in, out := &in.ActiveClients, &out.ActiveClients
		*out = new(int)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MiraCephFsStatus.
func (in *MiraCephFsStatus) DeepCopy() *MiraCephFsStatus {
	if in == nil {
		return nil
	}
	out := new(MiraCephFsStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MiraCephHyperConverge) DeepCopyInto(out *MiraCephHyperConverge) {
	*out = *in
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = make(v1.ResourceSpec, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make(map[string]MiraCephToleration, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MiraCephHyperConverge.
func (in *MiraCephHyperConverge) DeepCopy() *MiraCephHyperConverge {
	if in == nil {
		return nil
	}
	out := new(MiraCephHyperConverge)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MiraCephList) DeepCopyInto(out *MiraCephList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MiraCeph, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MiraCephList.
func (in *MiraCephList) DeepCopy() *MiraCephList {
	if in == nil {
		return nil
	}
	out := new(MiraCephList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MiraCephList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MiraCephLog) DeepCopyInto(out *MiraCephLog) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	if in.MiraCephClusterStatus != nil {
		in, out := &in.MiraCephClusterStatus, &out.MiraCephClusterStatus
		*out = new(MiraCephClusterStatus)
		(*in).DeepCopyInto(*out)
	}
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MiraCephLog.
func (in *MiraCephLog) DeepCopy() *MiraCephLog {
	if in == nil {
		return nil
	}
	out := new(MiraCephLog)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MiraCephLog) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MiraCephLogList) DeepCopyInto(out *MiraCephLogList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MiraCephLog, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MiraCephLogList.
func (in *MiraCephLogList) DeepCopy() *MiraCephLogList {
	if in == nil {
		return nil
	}
	out := new(MiraCephLogList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MiraCephLogList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MiraCephLogStatus) DeepCopyInto(out *MiraCephLogStatus) {
	*out = *in
	if in.Messages != nil {
		in, out := &in.Messages, &out.Messages
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MiraCephLogStatus.
func (in *MiraCephLogStatus) DeepCopy() *MiraCephLogStatus {
	if in == nil {
		return nil
	}
	out := new(MiraCephLogStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MiraCephMetadataServer) DeepCopyInto(out *MiraCephMetadataServer) {
	*out = *in
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(corev1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MiraCephMetadataServer.
func (in *MiraCephMetadataServer) DeepCopy() *MiraCephMetadataServer {
	if in == nil {
		return nil
	}
	out := new(MiraCephMetadataServer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MiraCephMultiSite) DeepCopyInto(out *MiraCephMultiSite) {
	*out = *in
	if in.Realms != nil {
		in, out := &in.Realms, &out.Realms
		*out = make([]*MiraCephRealm, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(MiraCephRealm)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.ZoneGroups != nil {
		in, out := &in.ZoneGroups, &out.ZoneGroups
		*out = make([]*MiraCephZoneGroup, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(MiraCephZoneGroup)
				**out = **in
			}
		}
	}
	if in.Zones != nil {
		in, out := &in.Zones, &out.Zones
		*out = make([]*MiraCephZone, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(MiraCephZone)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MiraCephMultiSite.
func (in *MiraCephMultiSite) DeepCopy() *MiraCephMultiSite {
	if in == nil {
		return nil
	}
	out := new(MiraCephMultiSite)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MiraCephNetworkSpec) DeepCopyInto(out *MiraCephNetworkSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MiraCephNetworkSpec.
func (in *MiraCephNetworkSpec) DeepCopy() *MiraCephNetworkSpec {
	if in == nil {
		return nil
	}
	out := new(MiraCephNetworkSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MiraCephNode) DeepCopyInto(out *MiraCephNode) {
	*out = *in
	if in.Roles != nil {
		in, out := &in.Roles, &out.Roles
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Crush != nil {
		in, out := &in.Crush, &out.Crush
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.NodeGroup != nil {
		in, out := &in.NodeGroup, &out.NodeGroup
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(corev1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	in.Selection.DeepCopyInto(&out.Selection)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MiraCephNode.
func (in *MiraCephNode) DeepCopy() *MiraCephNode {
	if in == nil {
		return nil
	}
	out := new(MiraCephNode)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MiraCephObjectStorage) DeepCopyInto(out *MiraCephObjectStorage) {
	*out = *in
	if in.Rgw != nil {
		in, out := &in.Rgw, &out.Rgw
		*out = new(MiraCephRGW)
		(*in).DeepCopyInto(*out)
	}
	if in.MultiSite != nil {
		in, out := &in.MultiSite, &out.MultiSite
		*out = new(MiraCephMultiSite)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MiraCephObjectStorage.
func (in *MiraCephObjectStorage) DeepCopy() *MiraCephObjectStorage {
	if in == nil {
		return nil
	}
	out := new(MiraCephObjectStorage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MiraCephPool) DeepCopyInto(out *MiraCephPool) {
	*out = *in
	in.MiraCephPoolSpec.DeepCopyInto(&out.MiraCephPoolSpec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MiraCephPool.
func (in *MiraCephPool) DeepCopy() *MiraCephPool {
	if in == nil {
		return nil
	}
	out := new(MiraCephPool)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MiraCephPoolSpec) DeepCopyInto(out *MiraCephPoolSpec) {
	*out = *in
	if in.Replicated != nil {
		in, out := &in.Replicated, &out.Replicated
		*out = new(MiraReplicatedSpec)
		**out = **in
	}
	if in.ErasureCoded != nil {
		in, out := &in.ErasureCoded, &out.ErasureCoded
		*out = new(MiraErasureCodedSpec)
		**out = **in
	}
	if in.Mirroring != nil {
		in, out := &in.Mirroring, &out.Mirroring
		*out = new(MiraPoolMirrorSpec)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MiraCephPoolSpec.
func (in *MiraCephPoolSpec) DeepCopy() *MiraCephPoolSpec {
	if in == nil {
		return nil
	}
	out := new(MiraCephPoolSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MiraCephRGW) DeepCopyInto(out *MiraCephRGW) {
	*out = *in
	if in.Users != nil {
		in, out := &in.Users, &out.Users
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Buckets != nil {
		in, out := &in.Buckets, &out.Buckets
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int)
		**out = **in
	}
	in.MetadataPool.DeepCopyInto(&out.MetadataPool)
	in.DataPool.DeepCopyInto(&out.DataPool)
	in.Gateway.DeepCopyInto(&out.Gateway)
	if in.SSLCert != nil {
		in, out := &in.SSLCert, &out.SSLCert
		*out = new(MiraCert)
		**out = **in
	}
	out.Zone = in.Zone
	in.HealthCheck.DeepCopyInto(&out.HealthCheck)
	if in.Ingress != nil {
		in, out := &in.Ingress, &out.Ingress
		*out = new(MiraIngress)
		(*in).DeepCopyInto(*out)
	}
	if in.ExternalSSL != nil {
		in, out := &in.ExternalSSL, &out.ExternalSSL
		*out = new(MiraCert)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MiraCephRGW.
func (in *MiraCephRGW) DeepCopy() *MiraCephRGW {
	if in == nil {
		return nil
	}
	out := new(MiraCephRGW)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MiraCephRealm) DeepCopyInto(out *MiraCephRealm) {
	*out = *in
	if in.Pull != nil {
		in, out := &in.Pull, &out.Pull
		*out = new(MiraCephRealmPull)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MiraCephRealm.
func (in *MiraCephRealm) DeepCopy() *MiraCephRealm {
	if in == nil {
		return nil
	}
	out := new(MiraCephRealm)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MiraCephRealmPull) DeepCopyInto(out *MiraCephRealmPull) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MiraCephRealmPull.
func (in *MiraCephRealmPull) DeepCopy() *MiraCephRealmPull {
	if in == nil {
		return nil
	}
	out := new(MiraCephRealmPull)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MiraCephSharedFilesystem) DeepCopyInto(out *MiraCephSharedFilesystem) {
	*out = *in
	if in.CephFS != nil {
		in, out := &in.CephFS, &out.CephFS
		*out = make([]MiraCephFS, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MiraCephSharedFilesystem.
func (in *MiraCephSharedFilesystem) DeepCopy() *MiraCephSharedFilesystem {
	if in == nil {
		return nil
	}
	out := new(MiraCephSharedFilesystem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MiraCephSpec) DeepCopyInto(out *MiraCephSpec) {
	*out = *in
	if in.Network != nil {
		in, out := &in.Network, &out.Network
		*out = new(MiraCephNetworkSpec)
		**out = **in
	}
	if in.Mgr != nil {
		in, out := &in.Mgr, &out.Mgr
		*out = new(Mgr)
		(*in).DeepCopyInto(*out)
	}
	if in.Nodes != nil {
		in, out := &in.Nodes, &out.Nodes
		*out = make([]*MiraCephNode, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(MiraCephNode)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.Pools != nil {
		in, out := &in.Pools, &out.Pools
		*out = make([]*MiraCephPool, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(MiraCephPool)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.Clients != nil {
		in, out := &in.Clients, &out.Clients
		*out = make([]*MiraCephClient, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(MiraCephClient)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.ObjectStorage != nil {
		in, out := &in.ObjectStorage, &out.ObjectStorage
		*out = new(MiraCephObjectStorage)
		(*in).DeepCopyInto(*out)
	}
	out.External = in.External
	if in.SharedFilesystem != nil {
		in, out := &in.SharedFilesystem, &out.SharedFilesystem
		*out = new(MiraCephSharedFilesystem)
		(*in).DeepCopyInto(*out)
	}
	if in.Ingress != nil {
		in, out := &in.Ingress, &out.Ingress
		*out = new(MiraIngress)
		(*in).DeepCopyInto(*out)
	}
	if in.HyperConverge != nil {
		in, out := &in.HyperConverge, &out.HyperConverge
		*out = new(MiraCephHyperConverge)
		(*in).DeepCopyInto(*out)
	}
	if in.RookConfig != nil {
		in, out := &in.RookConfig, &out.RookConfig
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.RBDMirror != nil {
		in, out := &in.RBDMirror, &out.RBDMirror
		*out = new(MiraRBDMirrorSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Rgw != nil {
		in, out := &in.Rgw, &out.Rgw
		*out = new(MiraCephRGW)
		(*in).DeepCopyInto(*out)
	}
	if in.ManageOsds != nil {
		in, out := &in.ManageOsds, &out.ManageOsds
		*out = new(bool)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MiraCephSpec.
func (in *MiraCephSpec) DeepCopy() *MiraCephSpec {
	if in == nil {
		return nil
	}
	out := new(MiraCephSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MiraCephSpecVersion) DeepCopyInto(out *MiraCephSpecVersion) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MiraCephSpecVersion.
func (in *MiraCephSpecVersion) DeepCopy() *MiraCephSpecVersion {
	if in == nil {
		return nil
	}
	out := new(MiraCephSpecVersion)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MiraCephStatus) DeepCopyInto(out *MiraCephStatus) {
	*out = *in
	in.Validation.DeepCopyInto(&out.Validation)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MiraCephStatus.
func (in *MiraCephStatus) DeepCopy() *MiraCephStatus {
	if in == nil {
		return nil
	}
	out := new(MiraCephStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MiraCephToleration) DeepCopyInto(out *MiraCephToleration) {
	*out = *in
	if in.Rules != nil {
		in, out := &in.Rules, &out.Rules
		*out = make([]corev1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MiraCephToleration.
func (in *MiraCephToleration) DeepCopy() *MiraCephToleration {
	if in == nil {
		return nil
	}
	out := new(MiraCephToleration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MiraCephZone) DeepCopyInto(out *MiraCephZone) {
	*out = *in
	in.MetadataPool.DeepCopyInto(&out.MetadataPool)
	in.DataPool.DeepCopyInto(&out.DataPool)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MiraCephZone.
func (in *MiraCephZone) DeepCopy() *MiraCephZone {
	if in == nil {
		return nil
	}
	out := new(MiraCephZone)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MiraCephZoneGroup) DeepCopyInto(out *MiraCephZoneGroup) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MiraCephZoneGroup.
func (in *MiraCephZoneGroup) DeepCopy() *MiraCephZoneGroup {
	if in == nil {
		return nil
	}
	out := new(MiraCephZoneGroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MiraCert) DeepCopyInto(out *MiraCert) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MiraCert.
func (in *MiraCert) DeepCopy() *MiraCert {
	if in == nil {
		return nil
	}
	out := new(MiraCert)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MiraCustomIngress) DeepCopyInto(out *MiraCustomIngress) {
	*out = *in
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MiraCustomIngress.
func (in *MiraCustomIngress) DeepCopy() *MiraCustomIngress {
	if in == nil {
		return nil
	}
	out := new(MiraCustomIngress)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MiraErasureCodedSpec) DeepCopyInto(out *MiraErasureCodedSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MiraErasureCodedSpec.
func (in *MiraErasureCodedSpec) DeepCopy() *MiraErasureCodedSpec {
	if in == nil {
		return nil
	}
	out := new(MiraErasureCodedSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MiraExternalRgwEndpoint) DeepCopyInto(out *MiraExternalRgwEndpoint) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MiraExternalRgwEndpoint.
func (in *MiraExternalRgwEndpoint) DeepCopy() *MiraExternalRgwEndpoint {
	if in == nil {
		return nil
	}
	out := new(MiraExternalRgwEndpoint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MiraGateway) DeepCopyInto(out *MiraGateway) {
	*out = *in
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(corev1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.ExternalRgwEndpoints != nil {
		in, out := &in.ExternalRgwEndpoints, &out.ExternalRgwEndpoints
		*out = make([]MiraExternalRgwEndpoint, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MiraGateway.
func (in *MiraGateway) DeepCopy() *MiraGateway {
	if in == nil {
		return nil
	}
	out := new(MiraGateway)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MiraIngress) DeepCopyInto(out *MiraIngress) {
	*out = *in
	out.MiraCert = in.MiraCert
	if in.CustomIngress != nil {
		in, out := &in.CustomIngress, &out.CustomIngress
		*out = new(MiraCustomIngress)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MiraIngress.
func (in *MiraIngress) DeepCopy() *MiraIngress {
	if in == nil {
		return nil
	}
	out := new(MiraIngress)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MiraObjectStoreBucketStatus) DeepCopyInto(out *MiraObjectStoreBucketStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MiraObjectStoreBucketStatus.
func (in *MiraObjectStoreBucketStatus) DeepCopy() *MiraObjectStoreBucketStatus {
	if in == nil {
		return nil
	}
	out := new(MiraObjectStoreBucketStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MiraObjectStoreUserStatus) DeepCopyInto(out *MiraObjectStoreUserStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MiraObjectStoreUserStatus.
func (in *MiraObjectStoreUserStatus) DeepCopy() *MiraObjectStoreUserStatus {
	if in == nil {
		return nil
	}
	out := new(MiraObjectStoreUserStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MiraPoolMirrorSpec) DeepCopyInto(out *MiraPoolMirrorSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MiraPoolMirrorSpec.
func (in *MiraPoolMirrorSpec) DeepCopy() *MiraPoolMirrorSpec {
	if in == nil {
		return nil
	}
	out := new(MiraPoolMirrorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MiraPoolStatus) DeepCopyInto(out *MiraPoolStatus) {
	*out = *in
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(v1.CephBlockPoolStatus)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MiraPoolStatus.
func (in *MiraPoolStatus) DeepCopy() *MiraPoolStatus {
	if in == nil {
		return nil
	}
	out := new(MiraPoolStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MiraRBDMirrorSpec) DeepCopyInto(out *MiraRBDMirrorSpec) {
	*out = *in
	if in.Peers != nil {
		in, out := &in.Peers, &out.Peers
		*out = make([]MiraRBDSecret, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MiraRBDMirrorSpec.
func (in *MiraRBDMirrorSpec) DeepCopy() *MiraRBDMirrorSpec {
	if in == nil {
		return nil
	}
	out := new(MiraRBDMirrorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MiraRBDSecret) DeepCopyInto(out *MiraRBDSecret) {
	*out = *in
	if in.Pools != nil {
		in, out := &in.Pools, &out.Pools
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MiraRBDSecret.
func (in *MiraRBDSecret) DeepCopy() *MiraRBDSecret {
	if in == nil {
		return nil
	}
	out := new(MiraRBDSecret)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MiraReplicatedSpec) DeepCopyInto(out *MiraReplicatedSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MiraReplicatedSpec.
func (in *MiraReplicatedSpec) DeepCopy() *MiraReplicatedSpec {
	if in == nil {
		return nil
	}
	out := new(MiraReplicatedSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MiraValidation) DeepCopyInto(out *MiraValidation) {
	*out = *in
	if in.Messages != nil {
		in, out := &in.Messages, &out.Messages
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MiraValidation.
func (in *MiraValidation) DeepCopy() *MiraValidation {
	if in == nil {
		return nil
	}
	out := new(MiraValidation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeCleanUpSpec) DeepCopyInto(out *NodeCleanUpSpec) {
	*out = *in
	if in.CleanUpByDevice != nil {
		in, out := &in.CleanUpByDevice, &out.CleanUpByDevice
		*out = make([]DeviceCleanUpSpec, len(*in))
		copy(*out, *in)
	}
	if in.CleanUpByOsdID != nil {
		in, out := &in.CleanUpByOsdID, &out.CleanUpByOsdID
		*out = make([]int, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeCleanUpSpec.
func (in *NodeCleanUpSpec) DeepCopy() *NodeCleanUpSpec {
	if in == nil {
		return nil
	}
	out := new(NodeCleanUpSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObjectStorageStatus) DeepCopyInto(out *ObjectStorageStatus) {
	*out = *in
	if in.ObjectStoreStatus != nil {
		in, out := &in.ObjectStoreStatus, &out.ObjectStoreStatus
		*out = new(v1.ObjectStoreStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.ObjectStoreUsersStatus != nil {
		in, out := &in.ObjectStoreUsersStatus, &out.ObjectStoreUsersStatus
		*out = make(map[string]MiraObjectStoreUserStatus, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ObjectStoreBucketsStatus != nil {
		in, out := &in.ObjectStoreBucketsStatus, &out.ObjectStoreBucketsStatus
		*out = make(map[string]MiraObjectStoreBucketStatus, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObjectStorageStatus.
func (in *ObjectStorageStatus) DeepCopy() *ObjectStorageStatus {
	if in == nil {
		return nil
	}
	out := new(ObjectStorageStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OsdDetails) DeepCopyInto(out *OsdDetails) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OsdDetails.
func (in *OsdDetails) DeepCopy() *OsdDetails {
	if in == nil {
		return nil
	}
	out := new(OsdDetails)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in OsdDeviceMapping) DeepCopyInto(out *OsdDeviceMapping) {
	{
		in := &in
		*out = make(OsdDeviceMapping, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
		return
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OsdDeviceMapping.
func (in OsdDeviceMapping) DeepCopy() OsdDeviceMapping {
	if in == nil {
		return nil
	}
	out := new(OsdDeviceMapping)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OsdMapping) DeepCopyInto(out *OsdMapping) {
	*out = *in
	if in.DeviceMapping != nil {
		in, out := &in.DeviceMapping, &out.DeviceMapping
		*out = make(map[string]DeviceInfo, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.RemoveStatus != nil {
		in, out := &in.RemoveStatus, &out.RemoveStatus
		*out = new(RemoveResult)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OsdMapping.
func (in *OsdMapping) DeepCopy() *OsdMapping {
	if in == nil {
		return nil
	}
	out := new(OsdMapping)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PoolDiskUsageStats) DeepCopyInto(out *PoolDiskUsageStats) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PoolDiskUsageStats.
func (in *PoolDiskUsageStats) DeepCopy() *PoolDiskUsageStats {
	if in == nil {
		return nil
	}
	out := new(PoolDiskUsageStats)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PoolUsageStats) DeepCopyInto(out *PoolUsageStats) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PoolUsageStats.
func (in *PoolUsageStats) DeepCopy() *PoolUsageStats {
	if in == nil {
		return nil
	}
	out := new(PoolUsageStats)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PvcStoredResults) DeepCopyInto(out *PvcStoredResults) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PvcStoredResults.
func (in *PvcStoredResults) DeepCopy() *PvcStoredResults {
	if in == nil {
		return nil
	}
	out := new(PvcStoredResults)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemoveResult) DeepCopyInto(out *RemoveResult) {
	*out = *in
	if in.OsdRemoveStatus != nil {
		in, out := &in.OsdRemoveStatus, &out.OsdRemoveStatus
		*out = new(RemoveStatus)
		**out = **in
	}
	if in.DeployRemoveStatus != nil {
		in, out := &in.DeployRemoveStatus, &out.DeployRemoveStatus
		*out = new(RemoveStatus)
		**out = **in
	}
	if in.DeviceCleanUpJob != nil {
		in, out := &in.DeviceCleanUpJob, &out.DeviceCleanUpJob
		*out = new(RemoveStatus)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemoveResult.
func (in *RemoveResult) DeepCopy() *RemoveResult {
	if in == nil {
		return nil
	}
	out := new(RemoveResult)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemoveStatus) DeepCopyInto(out *RemoveStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemoveStatus.
func (in *RemoveStatus) DeepCopy() *RemoveStatus {
	if in == nil {
		return nil
	}
	out := new(RemoveStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RequestRemoveInfo) DeepCopyInto(out *RequestRemoveInfo) {
	*out = *in
	if in.CleanUpMap != nil {
		in, out := &in.CleanUpMap, &out.CleanUpMap
		*out = make(map[string]HostMapping, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.Issues != nil {
		in, out := &in.Issues, &out.Issues
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Warnings != nil {
		in, out := &in.Warnings, &out.Warnings
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RequestRemoveInfo.
func (in *RequestRemoveInfo) DeepCopy() *RequestRemoveInfo {
	if in == nil {
		return nil
	}
	out := new(RequestRemoveInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SharedFilesystemStatus) DeepCopyInto(out *SharedFilesystemStatus) {
	*out = *in
	if in.CephFsStatus != nil {
		in, out := &in.CephFsStatus, &out.CephFsStatus
		*out = make(map[string]MiraCephFsStatus, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SharedFilesystemStatus.
func (in *SharedFilesystemStatus) DeepCopy() *SharedFilesystemStatus {
	if in == nil {
		return nil
	}
	out := new(SharedFilesystemStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UsageDetails) DeepCopyInto(out *UsageDetails) {
	*out = *in
	if in.ClassesDetail != nil {
		in, out := &in.ClassesDetail, &out.ClassesDetail
		*out = make(map[string]ClassUsageStats, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.PoolsDetail != nil {
		in, out := &in.PoolsDetail, &out.PoolsDetail
		*out = make(map[string]PoolUsageStats, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UsageDetails.
func (in *UsageDetails) DeepCopy() *UsageDetails {
	if in == nil {
		return nil
	}
	out := new(UsageDetails)
	in.DeepCopyInto(out)
	return out
}
