/*
Copyright 2022 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/Mirantis/mcc-api/pkg/apis/public/kaas/v1alpha1"
	scheme "github.com/Mirantis/mcc-api/pkg/client/internalclientset/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// BYOCredentialsGetter has a method to return a BYOCredentialInterface.
// A group's client should implement this interface.
type BYOCredentialsGetter interface {
	BYOCredentials(namespace string) BYOCredentialInterface
}

// BYOCredentialInterface has methods to work with BYOCredential resources.
type BYOCredentialInterface interface {
	Create(ctx context.Context, bYOCredential *v1alpha1.BYOCredential, opts v1.CreateOptions) (*v1alpha1.BYOCredential, error)
	Update(ctx context.Context, bYOCredential *v1alpha1.BYOCredential, opts v1.UpdateOptions) (*v1alpha1.BYOCredential, error)
	UpdateStatus(ctx context.Context, bYOCredential *v1alpha1.BYOCredential, opts v1.UpdateOptions) (*v1alpha1.BYOCredential, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.BYOCredential, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.BYOCredentialList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.BYOCredential, err error)
	BYOCredentialExpansion
}

// bYOCredentials implements BYOCredentialInterface
type bYOCredentials struct {
	client rest.Interface
	ns     string
}

// newBYOCredentials returns a BYOCredentials
func newBYOCredentials(c *KaasV1alpha1Client, namespace string) *bYOCredentials {
	return &bYOCredentials{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the bYOCredential, and returns the corresponding bYOCredential object, and an error if there is any.
func (c *bYOCredentials) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.BYOCredential, err error) {
	result = &v1alpha1.BYOCredential{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("byocredentials").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of BYOCredentials that match those selectors.
func (c *bYOCredentials) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.BYOCredentialList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.BYOCredentialList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("byocredentials").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested bYOCredentials.
func (c *bYOCredentials) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("byocredentials").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a bYOCredential and creates it.  Returns the server's representation of the bYOCredential, and an error, if there is any.
func (c *bYOCredentials) Create(ctx context.Context, bYOCredential *v1alpha1.BYOCredential, opts v1.CreateOptions) (result *v1alpha1.BYOCredential, err error) {
	result = &v1alpha1.BYOCredential{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("byocredentials").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(bYOCredential).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a bYOCredential and updates it. Returns the server's representation of the bYOCredential, and an error, if there is any.
func (c *bYOCredentials) Update(ctx context.Context, bYOCredential *v1alpha1.BYOCredential, opts v1.UpdateOptions) (result *v1alpha1.BYOCredential, err error) {
	result = &v1alpha1.BYOCredential{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("byocredentials").
		Name(bYOCredential.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(bYOCredential).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *bYOCredentials) UpdateStatus(ctx context.Context, bYOCredential *v1alpha1.BYOCredential, opts v1.UpdateOptions) (result *v1alpha1.BYOCredential, err error) {
	result = &v1alpha1.BYOCredential{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("byocredentials").
		Name(bYOCredential.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(bYOCredential).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the bYOCredential and deletes it. Returns an error if one occurs.
func (c *bYOCredentials) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("byocredentials").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *bYOCredentials) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("byocredentials").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched bYOCredential.
func (c *bYOCredentials) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.BYOCredential, err error) {
	result = &v1alpha1.BYOCredential{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("byocredentials").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
