/*
Copyright 2022 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen@v0.20.2. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/Mirantis/mcc-api/v2/pkg/apis/kaas/v1alpha1"
	scheme "github.com/Mirantis/mcc-api/v2/pkg/client/internalclientset/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ClusterReleasesGetter has a method to return a ClusterReleaseInterface.
// A group's client should implement this interface.
type ClusterReleasesGetter interface {
	ClusterReleases() ClusterReleaseInterface
}

// ClusterReleaseInterface has methods to work with ClusterRelease resources.
type ClusterReleaseInterface interface {
	Create(ctx context.Context, clusterRelease *v1alpha1.ClusterRelease, opts v1.CreateOptions) (*v1alpha1.ClusterRelease, error)
	Update(ctx context.Context, clusterRelease *v1alpha1.ClusterRelease, opts v1.UpdateOptions) (*v1alpha1.ClusterRelease, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.ClusterRelease, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.ClusterReleaseList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ClusterRelease, err error)
	ClusterReleaseExpansion
}

// clusterReleases implements ClusterReleaseInterface
type clusterReleases struct {
	client rest.Interface
}

// newClusterReleases returns a ClusterReleases
func newClusterReleases(c *KaasV1alpha1Client) *clusterReleases {
	return &clusterReleases{
		client: c.RESTClient(),
	}
}

// Get takes name of the clusterRelease, and returns the corresponding clusterRelease object, and an error if there is any.
func (c *clusterReleases) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ClusterRelease, err error) {
	result = &v1alpha1.ClusterRelease{}
	err = c.client.Get().
		Resource("clusterreleases").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ClusterReleases that match those selectors.
func (c *clusterReleases) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ClusterReleaseList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.ClusterReleaseList{}
	err = c.client.Get().
		Resource("clusterreleases").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested clusterReleases.
func (c *clusterReleases) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("clusterreleases").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a clusterRelease and creates it.  Returns the server's representation of the clusterRelease, and an error, if there is any.
func (c *clusterReleases) Create(ctx context.Context, clusterRelease *v1alpha1.ClusterRelease, opts v1.CreateOptions) (result *v1alpha1.ClusterRelease, err error) {
	result = &v1alpha1.ClusterRelease{}
	err = c.client.Post().
		Resource("clusterreleases").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(clusterRelease).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a clusterRelease and updates it. Returns the server's representation of the clusterRelease, and an error, if there is any.
func (c *clusterReleases) Update(ctx context.Context, clusterRelease *v1alpha1.ClusterRelease, opts v1.UpdateOptions) (result *v1alpha1.ClusterRelease, err error) {
	result = &v1alpha1.ClusterRelease{}
	err = c.client.Put().
		Resource("clusterreleases").
		Name(clusterRelease.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(clusterRelease).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the clusterRelease and deletes it. Returns an error if one occurs.
func (c *clusterReleases) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("clusterreleases").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *clusterReleases) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("clusterreleases").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched clusterRelease.
func (c *clusterReleases) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ClusterRelease, err error) {
	result = &v1alpha1.ClusterRelease{}
	err = c.client.Patch(pt).
		Resource("clusterreleases").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
