/*
Copyright 2022 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/Mirantis/mcc-api/pkg/apis/public/kaas/v1alpha1"
	scheme "github.com/Mirantis/mcc-api/pkg/client/internalclientset/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// EquinixMetalResourcesesGetter has a method to return a EquinixMetalResourcesInterface.
// A group's client should implement this interface.
type EquinixMetalResourcesesGetter interface {
	EquinixMetalResourceses(namespace string) EquinixMetalResourcesInterface
}

// EquinixMetalResourcesInterface has methods to work with EquinixMetalResources resources.
type EquinixMetalResourcesInterface interface {
	Create(ctx context.Context, equinixMetalResources *v1alpha1.EquinixMetalResources, opts v1.CreateOptions) (*v1alpha1.EquinixMetalResources, error)
	Update(ctx context.Context, equinixMetalResources *v1alpha1.EquinixMetalResources, opts v1.UpdateOptions) (*v1alpha1.EquinixMetalResources, error)
	UpdateStatus(ctx context.Context, equinixMetalResources *v1alpha1.EquinixMetalResources, opts v1.UpdateOptions) (*v1alpha1.EquinixMetalResources, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.EquinixMetalResources, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.EquinixMetalResourcesList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.EquinixMetalResources, err error)
	EquinixMetalResourcesExpansion
}

// equinixMetalResourceses implements EquinixMetalResourcesInterface
type equinixMetalResourceses struct {
	client rest.Interface
	ns     string
}

// newEquinixMetalResourceses returns a EquinixMetalResourceses
func newEquinixMetalResourceses(c *KaasV1alpha1Client, namespace string) *equinixMetalResourceses {
	return &equinixMetalResourceses{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the equinixMetalResources, and returns the corresponding equinixMetalResources object, and an error if there is any.
func (c *equinixMetalResourceses) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.EquinixMetalResources, err error) {
	result = &v1alpha1.EquinixMetalResources{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("equinixmetalresourceses").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of EquinixMetalResourceses that match those selectors.
func (c *equinixMetalResourceses) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.EquinixMetalResourcesList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.EquinixMetalResourcesList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("equinixmetalresourceses").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested equinixMetalResourceses.
func (c *equinixMetalResourceses) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("equinixmetalresourceses").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a equinixMetalResources and creates it.  Returns the server's representation of the equinixMetalResources, and an error, if there is any.
func (c *equinixMetalResourceses) Create(ctx context.Context, equinixMetalResources *v1alpha1.EquinixMetalResources, opts v1.CreateOptions) (result *v1alpha1.EquinixMetalResources, err error) {
	result = &v1alpha1.EquinixMetalResources{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("equinixmetalresourceses").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(equinixMetalResources).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a equinixMetalResources and updates it. Returns the server's representation of the equinixMetalResources, and an error, if there is any.
func (c *equinixMetalResourceses) Update(ctx context.Context, equinixMetalResources *v1alpha1.EquinixMetalResources, opts v1.UpdateOptions) (result *v1alpha1.EquinixMetalResources, err error) {
	result = &v1alpha1.EquinixMetalResources{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("equinixmetalresourceses").
		Name(equinixMetalResources.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(equinixMetalResources).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *equinixMetalResourceses) UpdateStatus(ctx context.Context, equinixMetalResources *v1alpha1.EquinixMetalResources, opts v1.UpdateOptions) (result *v1alpha1.EquinixMetalResources, err error) {
	result = &v1alpha1.EquinixMetalResources{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("equinixmetalresourceses").
		Name(equinixMetalResources.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(equinixMetalResources).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the equinixMetalResources and deletes it. Returns an error if one occurs.
func (c *equinixMetalResourceses) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("equinixmetalresourceses").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *equinixMetalResourceses) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("equinixmetalresourceses").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched equinixMetalResources.
func (c *equinixMetalResourceses) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.EquinixMetalResources, err error) {
	result = &v1alpha1.EquinixMetalResources{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("equinixmetalresourceses").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
