/*
Copyright 2022 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

type AWSCredentialExpansion interface{}

type AWSResourcesExpansion interface{}

type AzureCredentialExpansion interface{}

type AzureResourcesExpansion interface{}

type BYOCredentialExpansion interface{}

type CertificateExpansion interface{}

type CertificateConfigurationExpansion interface{}

type ClusterReleaseExpansion interface{}

type EquinixMetalCredentialExpansion interface{}

type EquinixMetalResourcesExpansion interface{}

type KaaSCephClusterExpansion interface{}

type KaaSCephOperationRequestExpansion interface{}

type KaaSReleaseExpansion interface{}

type LicenseExpansion interface{}

type MCCCertificateRequestExpansion interface{}

type MCCUpgradeExpansion interface{}

type MachinePoolExpansion interface{}

type OpenStackCredentialExpansion interface{}

type OpenStackResourcesExpansion interface{}

type ProxyExpansion interface{}

type PublicKeyExpansion interface{}

type RHELLicenseExpansion interface{}

type UnsupportedClustersExpansion interface{}

type VsphereCredentialExpansion interface{}

type VsphereResourcesExpansion interface{}
