/*
Copyright 2022 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen@v0.20.2. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/Mirantis/mcc-api/v2/pkg/apis/kaas/v1alpha1"
	scheme "github.com/Mirantis/mcc-api/v2/pkg/client/internalclientset/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// KaaSReleasesGetter has a method to return a KaaSReleaseInterface.
// A group's client should implement this interface.
type KaaSReleasesGetter interface {
	KaaSReleases() KaaSReleaseInterface
}

// KaaSReleaseInterface has methods to work with KaaSRelease resources.
type KaaSReleaseInterface interface {
	Create(ctx context.Context, kaaSRelease *v1alpha1.KaaSRelease, opts v1.CreateOptions) (*v1alpha1.KaaSRelease, error)
	Update(ctx context.Context, kaaSRelease *v1alpha1.KaaSRelease, opts v1.UpdateOptions) (*v1alpha1.KaaSRelease, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.KaaSRelease, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.KaaSReleaseList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.KaaSRelease, err error)
	KaaSReleaseExpansion
}

// kaaSReleases implements KaaSReleaseInterface
type kaaSReleases struct {
	client rest.Interface
}

// newKaaSReleases returns a KaaSReleases
func newKaaSReleases(c *KaasV1alpha1Client) *kaaSReleases {
	return &kaaSReleases{
		client: c.RESTClient(),
	}
}

// Get takes name of the kaaSRelease, and returns the corresponding kaaSRelease object, and an error if there is any.
func (c *kaaSReleases) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.KaaSRelease, err error) {
	result = &v1alpha1.KaaSRelease{}
	err = c.client.Get().
		Resource("kaasreleases").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of KaaSReleases that match those selectors.
func (c *kaaSReleases) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.KaaSReleaseList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.KaaSReleaseList{}
	err = c.client.Get().
		Resource("kaasreleases").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested kaaSReleases.
func (c *kaaSReleases) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("kaasreleases").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a kaaSRelease and creates it.  Returns the server's representation of the kaaSRelease, and an error, if there is any.
func (c *kaaSReleases) Create(ctx context.Context, kaaSRelease *v1alpha1.KaaSRelease, opts v1.CreateOptions) (result *v1alpha1.KaaSRelease, err error) {
	result = &v1alpha1.KaaSRelease{}
	err = c.client.Post().
		Resource("kaasreleases").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(kaaSRelease).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a kaaSRelease and updates it. Returns the server's representation of the kaaSRelease, and an error, if there is any.
func (c *kaaSReleases) Update(ctx context.Context, kaaSRelease *v1alpha1.KaaSRelease, opts v1.UpdateOptions) (result *v1alpha1.KaaSRelease, err error) {
	result = &v1alpha1.KaaSRelease{}
	err = c.client.Put().
		Resource("kaasreleases").
		Name(kaaSRelease.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(kaaSRelease).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the kaaSRelease and deletes it. Returns an error if one occurs.
func (c *kaaSReleases) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("kaasreleases").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *kaaSReleases) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("kaasreleases").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched kaaSRelease.
func (c *kaaSReleases) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.KaaSRelease, err error) {
	result = &v1alpha1.KaaSRelease{}
	err = c.client.Patch(pt).
		Resource("kaasreleases").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
