// +build !ignore_autogenerated

/*
Copyright 2022 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	types "github.com/elastic/go-sysinfo/types"
	corev1 "k8s.io/api/core/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentConfig) DeepCopyInto(out *AgentConfig) {
	*out = *in
	if in.Args != nil {
		in, out := &in.Args, &out.Args
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentConfig.
func (in *AgentConfig) DeepCopy() *AgentConfig {
	if in == nil {
		return nil
	}
	out := new(AgentConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterMaintenanceRequest) DeepCopyInto(out *ClusterMaintenanceRequest) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterMaintenanceRequest.
func (in *ClusterMaintenanceRequest) DeepCopy() *ClusterMaintenanceRequest {
	if in == nil {
		return nil
	}
	out := new(ClusterMaintenanceRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterMaintenanceRequest) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterMaintenanceRequestList) DeepCopyInto(out *ClusterMaintenanceRequestList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ClusterMaintenanceRequest, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterMaintenanceRequestList.
func (in *ClusterMaintenanceRequestList) DeepCopy() *ClusterMaintenanceRequestList {
	if in == nil {
		return nil
	}
	out := new(ClusterMaintenanceRequestList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterMaintenanceRequestList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterMaintenanceRequestSpec) DeepCopyInto(out *ClusterMaintenanceRequestSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterMaintenanceRequestSpec.
func (in *ClusterMaintenanceRequestSpec) DeepCopy() *ClusterMaintenanceRequestSpec {
	if in == nil {
		return nil
	}
	out := new(ClusterMaintenanceRequestSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterStateKey) DeepCopyInto(out *ClusterStateKey) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterStateKey.
func (in *ClusterStateKey) DeepCopy() *ClusterStateKey {
	if in == nil {
		return nil
	}
	out := new(ClusterStateKey)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterWorkloadLock) DeepCopyInto(out *ClusterWorkloadLock) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterWorkloadLock.
func (in *ClusterWorkloadLock) DeepCopy() *ClusterWorkloadLock {
	if in == nil {
		return nil
	}
	out := new(ClusterWorkloadLock)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterWorkloadLock) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterWorkloadLockList) DeepCopyInto(out *ClusterWorkloadLockList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ClusterWorkloadLock, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterWorkloadLockList.
func (in *ClusterWorkloadLockList) DeepCopy() *ClusterWorkloadLockList {
	if in == nil {
		return nil
	}
	out := new(ClusterWorkloadLockList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterWorkloadLockList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterWorkloadLockSpec) DeepCopyInto(out *ClusterWorkloadLockSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterWorkloadLockSpec.
func (in *ClusterWorkloadLockSpec) DeepCopy() *ClusterWorkloadLockSpec {
	if in == nil {
		return nil
	}
	out := new(ClusterWorkloadLockSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HelmBundle) DeepCopyInto(out *HelmBundle) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HelmBundle.
func (in *HelmBundle) DeepCopy() *HelmBundle {
	if in == nil {
		return nil
	}
	out := new(HelmBundle)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HelmBundle) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HelmBundleList) DeepCopyInto(out *HelmBundleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HelmBundle, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HelmBundleList.
func (in *HelmBundleList) DeepCopy() *HelmBundleList {
	if in == nil {
		return nil
	}
	out := new(HelmBundleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HelmBundleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HelmBundleSpec) DeepCopyInto(out *HelmBundleSpec) {
	*out = *in
	if in.Repositories != nil {
		in, out := &in.Repositories, &out.Repositories
		*out = make([]HelmRepositorySpec, len(*in))
		copy(*out, *in)
	}
	if in.Releases != nil {
		in, out := &in.Releases, &out.Releases
		*out = make([]HelmReleaseSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HelmBundleSpec.
func (in *HelmBundleSpec) DeepCopy() *HelmBundleSpec {
	if in == nil {
		return nil
	}
	out := new(HelmBundleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HelmBundleStatus) DeepCopyInto(out *HelmBundleStatus) {
	*out = *in
	if in.ReleaseStatuses != nil {
		in, out := &in.ReleaseStatuses, &out.ReleaseStatuses
		*out = make(map[string]HelmReleaseStatus, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HelmBundleStatus.
func (in *HelmBundleStatus) DeepCopy() *HelmBundleStatus {
	if in == nil {
		return nil
	}
	out := new(HelmBundleStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HelmReleaseSpec) DeepCopyInto(out *HelmReleaseSpec) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	in.Values.DeepCopyInto(&out.Values)
	if in.Requires != nil {
		in, out := &in.Requires, &out.Requires
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HelmReleaseSpec.
func (in *HelmReleaseSpec) DeepCopy() *HelmReleaseSpec {
	if in == nil {
		return nil
	}
	out := new(HelmReleaseSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HelmReleaseStatus) DeepCopyInto(out *HelmReleaseStatus) {
	*out = *in
	in.LastUpdateTime.DeepCopyInto(&out.LastUpdateTime)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HelmReleaseStatus.
func (in *HelmReleaseStatus) DeepCopy() *HelmReleaseStatus {
	if in == nil {
		return nil
	}
	out := new(HelmReleaseStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HelmRepositorySpec) DeepCopyInto(out *HelmRepositorySpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HelmRepositorySpec.
func (in *HelmRepositorySpec) DeepCopy() *HelmRepositorySpec {
	if in == nil {
		return nil
	}
	out := new(HelmRepositorySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostInfo) DeepCopyInto(out *HostInfo) {
	*out = *in
	if in.BootTime != nil {
		in, out := &in.BootTime, &out.BootTime
		*out = (*in).DeepCopy()
	}
	if in.OS != nil {
		in, out := &in.OS, &out.OS
		*out = new(types.OSInfo)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostInfo.
func (in *HostInfo) DeepCopy() *HostInfo {
	if in == nil {
		return nil
	}
	out := new(HostInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LCMAgentUpgradeStatus) DeepCopyInto(out *LCMAgentUpgradeStatus) {
	*out = *in
	in.StartedAt.DeepCopyInto(&out.StartedAt)
	in.FinishedAt.DeepCopyInto(&out.FinishedAt)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LCMAgentUpgradeStatus.
func (in *LCMAgentUpgradeStatus) DeepCopy() *LCMAgentUpgradeStatus {
	if in == nil {
		return nil
	}
	out := new(LCMAgentUpgradeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LCMCluster) DeepCopyInto(out *LCMCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LCMCluster.
func (in *LCMCluster) DeepCopy() *LCMCluster {
	if in == nil {
		return nil
	}
	out := new(LCMCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LCMCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LCMClusterEndpoint) DeepCopyInto(out *LCMClusterEndpoint) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LCMClusterEndpoint.
func (in *LCMClusterEndpoint) DeepCopy() *LCMClusterEndpoint {
	if in == nil {
		return nil
	}
	out := new(LCMClusterEndpoint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LCMClusterImages) DeepCopyInto(out *LCMClusterImages) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LCMClusterImages.
func (in *LCMClusterImages) DeepCopy() *LCMClusterImages {
	if in == nil {
		return nil
	}
	out := new(LCMClusterImages)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LCMClusterList) DeepCopyInto(out *LCMClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LCMCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LCMClusterList.
func (in *LCMClusterList) DeepCopy() *LCMClusterList {
	if in == nil {
		return nil
	}
	out := new(LCMClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LCMClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LCMClusterSpec) DeepCopyInto(out *LCMClusterSpec) {
	*out = *in
	if in.MachineTypes != nil {
		in, out := &in.MachineTypes, &out.MachineTypes
		*out = make(map[LCMMachineType]LCMStateItems, len(*in))
		for key, val := range *in {
			var outVal []LCMStateItem
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = make(LCMStateItems, len(*in))
				for i := range *in {
					(*in)[i].DeepCopyInto(&(*out)[i])
				}
			}
			(*out)[key] = outVal
		}
	}
	out.Components = in.Components
	out.TenantClusterEndpoint = in.TenantClusterEndpoint
	out.ManagementClusterEndpoint = in.ManagementClusterEndpoint
	if in.TokenTTL != nil {
		in, out := &in.TokenTTL, &out.TokenTTL
		*out = new(v1.Duration)
		**out = **in
	}
	if in.MinTokenRemainingTTL != nil {
		in, out := &in.MinTokenRemainingTTL, &out.MinTokenRemainingTTL
		*out = new(v1.Duration)
		**out = **in
	}
	if in.DedicatedControlPlane != nil {
		in, out := &in.DedicatedControlPlane, &out.DedicatedControlPlane
		*out = new(bool)
		**out = **in
	}
	out.Images = in.Images
	if in.OIDC != nil {
		in, out := &in.OIDC, &out.OIDC
		*out = new(LCMOIDCSettings)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LCMClusterSpec.
func (in *LCMClusterSpec) DeepCopy() *LCMClusterSpec {
	if in == nil {
		return nil
	}
	out := new(LCMClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LCMClusterState) DeepCopyInto(out *LCMClusterState) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LCMClusterState.
func (in *LCMClusterState) DeepCopy() *LCMClusterState {
	if in == nil {
		return nil
	}
	out := new(LCMClusterState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LCMClusterState) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LCMClusterStateList) DeepCopyInto(out *LCMClusterStateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LCMClusterState, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LCMClusterStateList.
func (in *LCMClusterStateList) DeepCopy() *LCMClusterStateList {
	if in == nil {
		return nil
	}
	out := new(LCMClusterStateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LCMClusterStateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LCMClusterStateSpec) DeepCopyInto(out *LCMClusterStateSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LCMClusterStateSpec.
func (in *LCMClusterStateSpec) DeepCopy() *LCMClusterStateSpec {
	if in == nil {
		return nil
	}
	out := new(LCMClusterStateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LCMClusterStateStatus) DeepCopyInto(out *LCMClusterStateStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LCMClusterStateStatus.
func (in *LCMClusterStateStatus) DeepCopy() *LCMClusterStateStatus {
	if in == nil {
		return nil
	}
	out := new(LCMClusterStateStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LCMClusterStatus) DeepCopyInto(out *LCMClusterStatus) {
	*out = *in
	out.Components = in.Components
	out.OIDC = in.OIDC
	if in.OIDCUpdateTime != nil {
		in, out := &in.OIDCUpdateTime, &out.OIDCUpdateTime
		*out = (*in).DeepCopy()
	}
	if in.OIDCSettingsHash != nil {
		in, out := &in.OIDCSettingsHash, &out.OIDCSettingsHash
		*out = new(string)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LCMClusterStatus.
func (in *LCMClusterStatus) DeepCopy() *LCMClusterStatus {
	if in == nil {
		return nil
	}
	out := new(LCMClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LCMComponents) DeepCopyInto(out *LCMComponents) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LCMComponents.
func (in *LCMComponents) DeepCopy() *LCMComponents {
	if in == nil {
		return nil
	}
	out := new(LCMComponents)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LCMComponentsStatus) DeepCopyInto(out *LCMComponentsStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LCMComponentsStatus.
func (in *LCMComponentsStatus) DeepCopy() *LCMComponentsStatus {
	if in == nil {
		return nil
	}
	out := new(LCMComponentsStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LCMMachine) DeepCopyInto(out *LCMMachine) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LCMMachine.
func (in *LCMMachine) DeepCopy() *LCMMachine {
	if in == nil {
		return nil
	}
	out := new(LCMMachine)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LCMMachine) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LCMMachineList) DeepCopyInto(out *LCMMachineList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LCMMachine, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LCMMachineList.
func (in *LCMMachineList) DeepCopy() *LCMMachineList {
	if in == nil {
		return nil
	}
	out := new(LCMMachineList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LCMMachineList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LCMMachineSpec) DeepCopyInto(out *LCMMachineSpec) {
	*out = *in
	out.Components = in.Components
	if in.StateItems != nil {
		in, out := &in.StateItems, &out.StateItems
		*out = make([]LCMStateItem, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.StateItemsOverwrites != nil {
		in, out := &in.StateItemsOverwrites, &out.StateItemsOverwrites
		*out = make(map[string]LCMParams, len(*in))
		for key, val := range *in {
			var outVal map[string]string
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = make(LCMParams, len(*in))
				for key, val := range *in {
					(*out)[key] = val
				}
			}
			(*out)[key] = outVal
		}
	}
	in.AgentConfig.DeepCopyInto(&out.AgentConfig)
	if in.SSHAuthorizedKeys != nil {
		in, out := &in.SSHAuthorizedKeys, &out.SSHAuthorizedKeys
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LCMMachineSpec.
func (in *LCMMachineSpec) DeepCopy() *LCMMachineSpec {
	if in == nil {
		return nil
	}
	out := new(LCMMachineSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LCMMachineStatus) DeepCopyInto(out *LCMMachineStatus) {
	*out = *in
	if in.StateItemStatuses != nil {
		in, out := &in.StateItemStatuses, &out.StateItemStatuses
		*out = make(map[string]LCMStateItemStatus, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.Addresses != nil {
		in, out := &in.Addresses, &out.Addresses
		*out = make([]corev1.NodeAddress, len(*in))
		copy(*out, *in)
	}
	if in.AgentUpgradeStatus != nil {
		in, out := &in.AgentUpgradeStatus, &out.AgentUpgradeStatus
		*out = new(LCMAgentUpgradeStatus)
		(*in).DeepCopyInto(*out)
	}
	out.Components = in.Components
	if in.Reboot != nil {
		in, out := &in.Reboot, &out.Reboot
		*out = new(RebootStatus)
		(*in).DeepCopyInto(*out)
	}
	in.HostInfo.DeepCopyInto(&out.HostInfo)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LCMMachineStatus.
func (in *LCMMachineStatus) DeepCopy() *LCMMachineStatus {
	if in == nil {
		return nil
	}
	out := new(LCMMachineStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LCMOIDCSettings) DeepCopyInto(out *LCMOIDCSettings) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LCMOIDCSettings.
func (in *LCMOIDCSettings) DeepCopy() *LCMOIDCSettings {
	if in == nil {
		return nil
	}
	out := new(LCMOIDCSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in LCMParams) DeepCopyInto(out *LCMParams) {
	{
		in := &in
		*out = make(LCMParams, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
		return
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LCMParams.
func (in LCMParams) DeepCopy() LCMParams {
	if in == nil {
		return nil
	}
	out := new(LCMParams)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LCMStateItem) DeepCopyInto(out *LCMStateItem) {
	*out = *in
	if in.Params != nil {
		in, out := &in.Params, &out.Params
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LCMStateItem.
func (in *LCMStateItem) DeepCopy() *LCMStateItem {
	if in == nil {
		return nil
	}
	out := new(LCMStateItem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LCMStateItemStatus) DeepCopyInto(out *LCMStateItemStatus) {
	*out = *in
	in.Result.DeepCopyInto(&out.Result)
	in.StartedAt.DeepCopyInto(&out.StartedAt)
	in.FinishedAt.DeepCopyInto(&out.FinishedAt)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LCMStateItemStatus.
func (in *LCMStateItemStatus) DeepCopy() *LCMStateItemStatus {
	if in == nil {
		return nil
	}
	out := new(LCMStateItemStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in LCMStateItems) DeepCopyInto(out *LCMStateItems) {
	{
		in := &in
		*out = make(LCMStateItems, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
		return
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LCMStateItems.
func (in LCMStateItems) DeepCopy() LCMStateItems {
	if in == nil {
		return nil
	}
	out := new(LCMStateItems)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LicenseSecret) DeepCopyInto(out *LicenseSecret) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LicenseSecret.
func (in *LicenseSecret) DeepCopy() *LicenseSecret {
	if in == nil {
		return nil
	}
	out := new(LicenseSecret)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LicenseSecretItem) DeepCopyInto(out *LicenseSecretItem) {
	*out = *in
	out.Secret = in.Secret
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LicenseSecretItem.
func (in *LicenseSecretItem) DeepCopy() *LicenseSecretItem {
	if in == nil {
		return nil
	}
	out := new(LicenseSecretItem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LicenseSubscriptionSpec) DeepCopyInto(out *LicenseSubscriptionSpec) {
	*out = *in
	if in.PoolIDs != nil {
		in, out := &in.PoolIDs, &out.PoolIDs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.Password = in.Password
	out.ActivationKey = in.ActivationKey
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LicenseSubscriptionSpec.
func (in *LicenseSubscriptionSpec) DeepCopy() *LicenseSubscriptionSpec {
	if in == nil {
		return nil
	}
	out := new(LicenseSubscriptionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LicenseSubscriptionStatus) DeepCopyInto(out *LicenseSubscriptionStatus) {
	*out = *in
	in.LastAttemptTime.DeepCopyInto(&out.LastAttemptTime)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LicenseSubscriptionStatus.
func (in *LicenseSubscriptionStatus) DeepCopy() *LicenseSubscriptionStatus {
	if in == nil {
		return nil
	}
	out := new(LicenseSubscriptionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeMaintenanceRequest) DeepCopyInto(out *NodeMaintenanceRequest) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeMaintenanceRequest.
func (in *NodeMaintenanceRequest) DeepCopy() *NodeMaintenanceRequest {
	if in == nil {
		return nil
	}
	out := new(NodeMaintenanceRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NodeMaintenanceRequest) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeMaintenanceRequestList) DeepCopyInto(out *NodeMaintenanceRequestList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NodeMaintenanceRequest, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeMaintenanceRequestList.
func (in *NodeMaintenanceRequestList) DeepCopy() *NodeMaintenanceRequestList {
	if in == nil {
		return nil
	}
	out := new(NodeMaintenanceRequestList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NodeMaintenanceRequestList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeMaintenanceRequestSpec) DeepCopyInto(out *NodeMaintenanceRequestSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeMaintenanceRequestSpec.
func (in *NodeMaintenanceRequestSpec) DeepCopy() *NodeMaintenanceRequestSpec {
	if in == nil {
		return nil
	}
	out := new(NodeMaintenanceRequestSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeWorkloadLock) DeepCopyInto(out *NodeWorkloadLock) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeWorkloadLock.
func (in *NodeWorkloadLock) DeepCopy() *NodeWorkloadLock {
	if in == nil {
		return nil
	}
	out := new(NodeWorkloadLock)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NodeWorkloadLock) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeWorkloadLockList) DeepCopyInto(out *NodeWorkloadLockList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NodeWorkloadLock, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeWorkloadLockList.
func (in *NodeWorkloadLockList) DeepCopy() *NodeWorkloadLockList {
	if in == nil {
		return nil
	}
	out := new(NodeWorkloadLockList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NodeWorkloadLockList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeWorkloadLockSpec) DeepCopyInto(out *NodeWorkloadLockSpec) {
	*out = *in
	out.ClusterWorkloadLockSpec = in.ClusterWorkloadLockSpec
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeWorkloadLockSpec.
func (in *NodeWorkloadLockSpec) DeepCopy() *NodeWorkloadLockSpec {
	if in == nil {
		return nil
	}
	out := new(NodeWorkloadLockSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RHELLicenseSubscription) DeepCopyInto(out *RHELLicenseSubscription) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RHELLicenseSubscription.
func (in *RHELLicenseSubscription) DeepCopy() *RHELLicenseSubscription {
	if in == nil {
		return nil
	}
	out := new(RHELLicenseSubscription)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RHELLicenseSubscription) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RHELLicenseSubscriptionList) DeepCopyInto(out *RHELLicenseSubscriptionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RHELLicenseSubscription, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RHELLicenseSubscriptionList.
func (in *RHELLicenseSubscriptionList) DeepCopy() *RHELLicenseSubscriptionList {
	if in == nil {
		return nil
	}
	out := new(RHELLicenseSubscriptionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RHELLicenseSubscriptionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RebootStatus) DeepCopyInto(out *RebootStatus) {
	*out = *in
	in.RequestedAt.DeepCopyInto(&out.RequestedAt)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RebootStatus.
func (in *RebootStatus) DeepCopy() *RebootStatus {
	if in == nil {
		return nil
	}
	out := new(RebootStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadLockStatus) DeepCopyInto(out *WorkloadLockStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadLockStatus.
func (in *WorkloadLockStatus) DeepCopy() *WorkloadLockStatus {
	if in == nil {
		return nil
	}
	out := new(WorkloadLockStatus)
	in.DeepCopyInto(out)
	return out
}
