//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2022 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by deepcopy-gen@v0.24.4. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BareMetalHostProfile) DeepCopyInto(out *BareMetalHostProfile) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BareMetalHostProfile.
func (in *BareMetalHostProfile) DeepCopy() *BareMetalHostProfile {
	if in == nil {
		return nil
	}
	out := new(BareMetalHostProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BareMetalHostProfile) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BareMetalHostProfileList) DeepCopyInto(out *BareMetalHostProfileList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BareMetalHostProfile, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BareMetalHostProfileList.
func (in *BareMetalHostProfileList) DeepCopy() *BareMetalHostProfileList {
	if in == nil {
		return nil
	}
	out := new(BareMetalHostProfileList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BareMetalHostProfileList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BareMetalHostProfileSpec) DeepCopyInto(out *BareMetalHostProfileSpec) {
	*out = *in
	in.GrubConfig.DeepCopyInto(&out.GrubConfig)
	if in.Devices != nil {
		in, out := &in.Devices, &out.Devices
		*out = make([]Device, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SoftRaidDevices != nil {
		in, out := &in.SoftRaidDevices, &out.SoftRaidDevices
		*out = make([]SoftRaidDevice, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.VolumeGroups != nil {
		in, out := &in.VolumeGroups, &out.VolumeGroups
		*out = make([]VG, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LogicalVolumes != nil {
		in, out := &in.LogicalVolumes, &out.LogicalVolumes
		*out = make([]LV, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.FileSystems != nil {
		in, out := &in.FileSystems, &out.FileSystems
		*out = make([]FileSystem, len(*in))
		copy(*out, *in)
	}
	in.KernelParameters.DeepCopyInto(&out.KernelParameters)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BareMetalHostProfileSpec.
func (in *BareMetalHostProfileSpec) DeepCopy() *BareMetalHostProfileSpec {
	if in == nil {
		return nil
	}
	out := new(BareMetalHostProfileSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BareMetalHostProfileStatus) DeepCopyInto(out *BareMetalHostProfileStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BareMetalHostProfileStatus.
func (in *BareMetalHostProfileStatus) DeepCopy() *BareMetalHostProfileStatus {
	if in == nil {
		return nil
	}
	out := new(BareMetalHostProfileStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Device) DeepCopyInto(out *Device) {
	*out = *in
	in.Device.DeepCopyInto(&out.Device)
	if in.Partitions != nil {
		in, out := &in.Partitions, &out.Partitions
		*out = make([]DiskPartition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Device.
func (in *Device) DeepCopy() *Device {
	if in == nil {
		return nil
	}
	out := new(Device)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeviceFilter) DeepCopyInto(out *DeviceFilter) {
	*out = *in
	out.MinSize = in.MinSize.DeepCopy()
	out.MaxSize = in.MaxSize.DeepCopy()
	if in.UseFor != nil {
		in, out := &in.UseFor, &out.UseFor
		*out = make([]DeviceUseFor, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeviceFilter.
func (in *DeviceFilter) DeepCopy() *DeviceFilter {
	if in == nil {
		return nil
	}
	out := new(DeviceFilter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiskPartition) DeepCopyInto(out *DiskPartition) {
	*out = *in
	out.Size = in.Size.DeepCopy()
	if in.Flags != nil {
		in, out := &in.Flags, &out.Flags
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.Device = in.Device
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiskPartition.
func (in *DiskPartition) DeepCopy() *DiskPartition {
	if in == nil {
		return nil
	}
	out := new(DiskPartition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FileSystem) DeepCopyInto(out *FileSystem) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FileSystem.
func (in *FileSystem) DeepCopy() *FileSystem {
	if in == nil {
		return nil
	}
	out := new(FileSystem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GrubConfig) DeepCopyInto(out *GrubConfig) {
	*out = *in
	if in.ToDevices != nil {
		in, out := &in.ToDevices, &out.ToDevices
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.DefaultGrubOptions != nil {
		in, out := &in.DefaultGrubOptions, &out.DefaultGrubOptions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GrubConfig.
func (in *GrubConfig) DeepCopy() *GrubConfig {
	if in == nil {
		return nil
	}
	out := new(GrubConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KernelModule) DeepCopyInto(out *KernelModule) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KernelModule.
func (in *KernelModule) DeepCopy() *KernelModule {
	if in == nil {
		return nil
	}
	out := new(KernelModule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KernelParameters) DeepCopyInto(out *KernelParameters) {
	*out = *in
	if in.Sysctl != nil {
		in, out := &in.Sysctl, &out.Sysctl
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Modules != nil {
		in, out := &in.Modules, &out.Modules
		*out = make([]KernelModule, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KernelParameters.
func (in *KernelParameters) DeepCopy() *KernelParameters {
	if in == nil {
		return nil
	}
	out := new(KernelParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LV) DeepCopyInto(out *LV) {
	*out = *in
	out.Size = in.Size.DeepCopy()
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LV.
func (in *LV) DeepCopy() *LV {
	if in == nil {
		return nil
	}
	out := new(LV)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PVFilter) DeepCopyInto(out *PVFilter) {
	*out = *in
	out.MinSize = in.MinSize.DeepCopy()
	out.MaxSize = in.MaxSize.DeepCopy()
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PVFilter.
func (in *PVFilter) DeepCopy() *PVFilter {
	if in == nil {
		return nil
	}
	out := new(PVFilter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SoftRaidDevice) DeepCopyInto(out *SoftRaidDevice) {
	*out = *in
	if in.Devices != nil {
		in, out := &in.Devices, &out.Devices
		*out = make([]PVFilter, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SoftRaidDevice.
func (in *SoftRaidDevice) DeepCopy() *SoftRaidDevice {
	if in == nil {
		return nil
	}
	out := new(SoftRaidDevice)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Storage) DeepCopyInto(out *Storage) {
	*out = *in
	out.Storage = in.Storage
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Storage.
func (in *Storage) DeepCopy() *Storage {
	if in == nil {
		return nil
	}
	out := new(Storage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VG) DeepCopyInto(out *VG) {
	*out = *in
	out.MinSize = in.MinSize.DeepCopy()
	if in.Devices != nil {
		in, out := &in.Devices, &out.Devices
		*out = make([]PVFilter, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VG.
func (in *VG) DeepCopy() *VG {
	if in == nil {
		return nil
	}
	out := new(VG)
	in.DeepCopyInto(out)
	return out
}
