/*
Copyright 2022 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen@v0.20.2. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/Mirantis/mcc-api/v2/pkg/apis/kaas/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeMetalLBConfigs implements MetalLBConfigInterface
type FakeMetalLBConfigs struct {
	Fake *FakeKaasV1alpha1
	ns   string
}

var metallbconfigsResource = schema.GroupVersionResource{Group: "kaas.mirantis.com", Version: "v1alpha1", Resource: "metallbconfigs"}

var metallbconfigsKind = schema.GroupVersionKind{Group: "kaas.mirantis.com", Version: "v1alpha1", Kind: "MetalLBConfig"}

// Get takes name of the metalLBConfig, and returns the corresponding metalLBConfig object, and an error if there is any.
func (c *FakeMetalLBConfigs) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.MetalLBConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(metallbconfigsResource, c.ns, name), &v1alpha1.MetalLBConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MetalLBConfig), err
}

// List takes label and field selectors, and returns the list of MetalLBConfigs that match those selectors.
func (c *FakeMetalLBConfigs) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.MetalLBConfigList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(metallbconfigsResource, metallbconfigsKind, c.ns, opts), &v1alpha1.MetalLBConfigList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.MetalLBConfigList{ListMeta: obj.(*v1alpha1.MetalLBConfigList).ListMeta}
	for _, item := range obj.(*v1alpha1.MetalLBConfigList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested metalLBConfigs.
func (c *FakeMetalLBConfigs) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(metallbconfigsResource, c.ns, opts))

}

// Create takes the representation of a metalLBConfig and creates it.  Returns the server's representation of the metalLBConfig, and an error, if there is any.
func (c *FakeMetalLBConfigs) Create(ctx context.Context, metalLBConfig *v1alpha1.MetalLBConfig, opts v1.CreateOptions) (result *v1alpha1.MetalLBConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(metallbconfigsResource, c.ns, metalLBConfig), &v1alpha1.MetalLBConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MetalLBConfig), err
}

// Update takes the representation of a metalLBConfig and updates it. Returns the server's representation of the metalLBConfig, and an error, if there is any.
func (c *FakeMetalLBConfigs) Update(ctx context.Context, metalLBConfig *v1alpha1.MetalLBConfig, opts v1.UpdateOptions) (result *v1alpha1.MetalLBConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(metallbconfigsResource, c.ns, metalLBConfig), &v1alpha1.MetalLBConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MetalLBConfig), err
}

// Delete takes name of the metalLBConfig and deletes it. Returns an error if one occurs.
func (c *FakeMetalLBConfigs) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(metallbconfigsResource, c.ns, name), &v1alpha1.MetalLBConfig{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeMetalLBConfigs) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(metallbconfigsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.MetalLBConfigList{})
	return err
}

// Patch applies the patch and returns the patched metalLBConfig.
func (c *FakeMetalLBConfigs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.MetalLBConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(metallbconfigsResource, c.ns, name, pt, data, subresources...), &v1alpha1.MetalLBConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MetalLBConfig), err
}
