/*
Copyright 2022 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/Mirantis/mcc-api/pkg/apis/public/kaas/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeKaaSReleases implements KaaSReleaseInterface
type FakeKaaSReleases struct {
	Fake *FakeKaasV1alpha1
}

var kaasreleasesResource = schema.GroupVersionResource{Group: "kaas.mirantis.com", Version: "v1alpha1", Resource: "kaasreleases"}

var kaasreleasesKind = schema.GroupVersionKind{Group: "kaas.mirantis.com", Version: "v1alpha1", Kind: "KaaSRelease"}

// Get takes name of the kaaSRelease, and returns the corresponding kaaSRelease object, and an error if there is any.
func (c *FakeKaaSReleases) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.KaaSRelease, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(kaasreleasesResource, name), &v1alpha1.KaaSRelease{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.KaaSRelease), err
}

// List takes label and field selectors, and returns the list of KaaSReleases that match those selectors.
func (c *FakeKaaSReleases) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.KaaSReleaseList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(kaasreleasesResource, kaasreleasesKind, opts), &v1alpha1.KaaSReleaseList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.KaaSReleaseList{ListMeta: obj.(*v1alpha1.KaaSReleaseList).ListMeta}
	for _, item := range obj.(*v1alpha1.KaaSReleaseList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested kaaSReleases.
func (c *FakeKaaSReleases) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(kaasreleasesResource, opts))
}

// Create takes the representation of a kaaSRelease and creates it.  Returns the server's representation of the kaaSRelease, and an error, if there is any.
func (c *FakeKaaSReleases) Create(ctx context.Context, kaaSRelease *v1alpha1.KaaSRelease, opts v1.CreateOptions) (result *v1alpha1.KaaSRelease, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(kaasreleasesResource, kaaSRelease), &v1alpha1.KaaSRelease{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.KaaSRelease), err
}

// Update takes the representation of a kaaSRelease and updates it. Returns the server's representation of the kaaSRelease, and an error, if there is any.
func (c *FakeKaaSReleases) Update(ctx context.Context, kaaSRelease *v1alpha1.KaaSRelease, opts v1.UpdateOptions) (result *v1alpha1.KaaSRelease, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(kaasreleasesResource, kaaSRelease), &v1alpha1.KaaSRelease{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.KaaSRelease), err
}

// Delete takes name of the kaaSRelease and deletes it. Returns an error if one occurs.
func (c *FakeKaaSReleases) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(kaasreleasesResource, name), &v1alpha1.KaaSRelease{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeKaaSReleases) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(kaasreleasesResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.KaaSReleaseList{})
	return err
}

// Patch applies the patch and returns the patched kaaSRelease.
func (c *FakeKaaSReleases) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.KaaSRelease, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(kaasreleasesResource, name, pt, data, subresources...), &v1alpha1.KaaSRelease{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.KaaSRelease), err
}
