/*
Copyright 2022 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen@v0.20.2. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/Mirantis/mcc-api/v2/pkg/apis/kaas/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeVsphereResourceses implements VsphereResourcesInterface
type FakeVsphereResourceses struct {
	Fake *FakeKaasV1alpha1
	ns   string
}

var vsphereresourcesesResource = schema.GroupVersionResource{Group: "kaas.mirantis.com", Version: "v1alpha1", Resource: "vsphereresourceses"}

var vsphereresourcesesKind = schema.GroupVersionKind{Group: "kaas.mirantis.com", Version: "v1alpha1", Kind: "VsphereResources"}

// Get takes name of the vsphereResources, and returns the corresponding vsphereResources object, and an error if there is any.
func (c *FakeVsphereResourceses) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.VsphereResources, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(vsphereresourcesesResource, c.ns, name), &v1alpha1.VsphereResources{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VsphereResources), err
}

// List takes label and field selectors, and returns the list of VsphereResourceses that match those selectors.
func (c *FakeVsphereResourceses) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.VsphereResourcesList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(vsphereresourcesesResource, vsphereresourcesesKind, c.ns, opts), &v1alpha1.VsphereResourcesList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.VsphereResourcesList{ListMeta: obj.(*v1alpha1.VsphereResourcesList).ListMeta}
	for _, item := range obj.(*v1alpha1.VsphereResourcesList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested vsphereResourceses.
func (c *FakeVsphereResourceses) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(vsphereresourcesesResource, c.ns, opts))

}

// Create takes the representation of a vsphereResources and creates it.  Returns the server's representation of the vsphereResources, and an error, if there is any.
func (c *FakeVsphereResourceses) Create(ctx context.Context, vsphereResources *v1alpha1.VsphereResources, opts v1.CreateOptions) (result *v1alpha1.VsphereResources, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(vsphereresourcesesResource, c.ns, vsphereResources), &v1alpha1.VsphereResources{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VsphereResources), err
}

// Update takes the representation of a vsphereResources and updates it. Returns the server's representation of the vsphereResources, and an error, if there is any.
func (c *FakeVsphereResourceses) Update(ctx context.Context, vsphereResources *v1alpha1.VsphereResources, opts v1.UpdateOptions) (result *v1alpha1.VsphereResources, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(vsphereresourcesesResource, c.ns, vsphereResources), &v1alpha1.VsphereResources{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VsphereResources), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeVsphereResourceses) UpdateStatus(ctx context.Context, vsphereResources *v1alpha1.VsphereResources, opts v1.UpdateOptions) (*v1alpha1.VsphereResources, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(vsphereresourcesesResource, "status", c.ns, vsphereResources), &v1alpha1.VsphereResources{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VsphereResources), err
}

// Delete takes name of the vsphereResources and deletes it. Returns an error if one occurs.
func (c *FakeVsphereResourceses) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(vsphereresourcesesResource, c.ns, name), &v1alpha1.VsphereResources{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeVsphereResourceses) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(vsphereresourcesesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.VsphereResourcesList{})
	return err
}

// Patch applies the patch and returns the patched vsphereResources.
func (c *FakeVsphereResourceses) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.VsphereResources, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(vsphereresourcesesResource, c.ns, name, pt, data, subresources...), &v1alpha1.VsphereResources{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VsphereResources), err
}
