/*
Copyright 2022 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/Mirantis/mcc-api/v2/pkg/apis/public/kaas/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeKaaSCephClusters implements KaaSCephClusterInterface
type FakeKaaSCephClusters struct {
	Fake *FakeKaasV1alpha1
	ns   string
}

var kaascephclustersResource = schema.GroupVersionResource{Group: "kaas.mirantis.com", Version: "v1alpha1", Resource: "kaascephclusters"}

var kaascephclustersKind = schema.GroupVersionKind{Group: "kaas.mirantis.com", Version: "v1alpha1", Kind: "KaaSCephCluster"}

// Get takes name of the kaaSCephCluster, and returns the corresponding kaaSCephCluster object, and an error if there is any.
func (c *FakeKaaSCephClusters) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.KaaSCephCluster, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(kaascephclustersResource, c.ns, name), &v1alpha1.KaaSCephCluster{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.KaaSCephCluster), err
}

// List takes label and field selectors, and returns the list of KaaSCephClusters that match those selectors.
func (c *FakeKaaSCephClusters) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.KaaSCephClusterList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(kaascephclustersResource, kaascephclustersKind, c.ns, opts), &v1alpha1.KaaSCephClusterList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.KaaSCephClusterList{ListMeta: obj.(*v1alpha1.KaaSCephClusterList).ListMeta}
	for _, item := range obj.(*v1alpha1.KaaSCephClusterList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested kaaSCephClusters.
func (c *FakeKaaSCephClusters) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(kaascephclustersResource, c.ns, opts))

}

// Create takes the representation of a kaaSCephCluster and creates it.  Returns the server's representation of the kaaSCephCluster, and an error, if there is any.
func (c *FakeKaaSCephClusters) Create(ctx context.Context, kaaSCephCluster *v1alpha1.KaaSCephCluster, opts v1.CreateOptions) (result *v1alpha1.KaaSCephCluster, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(kaascephclustersResource, c.ns, kaaSCephCluster), &v1alpha1.KaaSCephCluster{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.KaaSCephCluster), err
}

// Update takes the representation of a kaaSCephCluster and updates it. Returns the server's representation of the kaaSCephCluster, and an error, if there is any.
func (c *FakeKaaSCephClusters) Update(ctx context.Context, kaaSCephCluster *v1alpha1.KaaSCephCluster, opts v1.UpdateOptions) (result *v1alpha1.KaaSCephCluster, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(kaascephclustersResource, c.ns, kaaSCephCluster), &v1alpha1.KaaSCephCluster{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.KaaSCephCluster), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeKaaSCephClusters) UpdateStatus(ctx context.Context, kaaSCephCluster *v1alpha1.KaaSCephCluster, opts v1.UpdateOptions) (*v1alpha1.KaaSCephCluster, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(kaascephclustersResource, "status", c.ns, kaaSCephCluster), &v1alpha1.KaaSCephCluster{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.KaaSCephCluster), err
}

// Delete takes name of the kaaSCephCluster and deletes it. Returns an error if one occurs.
func (c *FakeKaaSCephClusters) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(kaascephclustersResource, c.ns, name), &v1alpha1.KaaSCephCluster{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeKaaSCephClusters) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(kaascephclustersResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.KaaSCephClusterList{})
	return err
}

// Patch applies the patch and returns the patched kaaSCephCluster.
func (c *FakeKaaSCephClusters) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.KaaSCephCluster, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(kaascephclustersResource, c.ns, name, pt, data, subresources...), &v1alpha1.KaaSCephCluster{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.KaaSCephCluster), err
}
