/*
Copyright 2022 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen@v0.20.2. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/Mirantis/mcc-api/v2/pkg/apis/kaas/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeVsphereCredentials implements VsphereCredentialInterface
type FakeVsphereCredentials struct {
	Fake *FakeKaasV1alpha1
	ns   string
}

var vspherecredentialsResource = schema.GroupVersionResource{Group: "kaas.mirantis.com", Version: "v1alpha1", Resource: "vspherecredentials"}

var vspherecredentialsKind = schema.GroupVersionKind{Group: "kaas.mirantis.com", Version: "v1alpha1", Kind: "VsphereCredential"}

// Get takes name of the vsphereCredential, and returns the corresponding vsphereCredential object, and an error if there is any.
func (c *FakeVsphereCredentials) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.VsphereCredential, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(vspherecredentialsResource, c.ns, name), &v1alpha1.VsphereCredential{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VsphereCredential), err
}

// List takes label and field selectors, and returns the list of VsphereCredentials that match those selectors.
func (c *FakeVsphereCredentials) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.VsphereCredentialList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(vspherecredentialsResource, vspherecredentialsKind, c.ns, opts), &v1alpha1.VsphereCredentialList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.VsphereCredentialList{ListMeta: obj.(*v1alpha1.VsphereCredentialList).ListMeta}
	for _, item := range obj.(*v1alpha1.VsphereCredentialList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested vsphereCredentials.
func (c *FakeVsphereCredentials) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(vspherecredentialsResource, c.ns, opts))

}

// Create takes the representation of a vsphereCredential and creates it.  Returns the server's representation of the vsphereCredential, and an error, if there is any.
func (c *FakeVsphereCredentials) Create(ctx context.Context, vsphereCredential *v1alpha1.VsphereCredential, opts v1.CreateOptions) (result *v1alpha1.VsphereCredential, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(vspherecredentialsResource, c.ns, vsphereCredential), &v1alpha1.VsphereCredential{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VsphereCredential), err
}

// Update takes the representation of a vsphereCredential and updates it. Returns the server's representation of the vsphereCredential, and an error, if there is any.
func (c *FakeVsphereCredentials) Update(ctx context.Context, vsphereCredential *v1alpha1.VsphereCredential, opts v1.UpdateOptions) (result *v1alpha1.VsphereCredential, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(vspherecredentialsResource, c.ns, vsphereCredential), &v1alpha1.VsphereCredential{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VsphereCredential), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeVsphereCredentials) UpdateStatus(ctx context.Context, vsphereCredential *v1alpha1.VsphereCredential, opts v1.UpdateOptions) (*v1alpha1.VsphereCredential, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(vspherecredentialsResource, "status", c.ns, vsphereCredential), &v1alpha1.VsphereCredential{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VsphereCredential), err
}

// Delete takes name of the vsphereCredential and deletes it. Returns an error if one occurs.
func (c *FakeVsphereCredentials) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(vspherecredentialsResource, c.ns, name), &v1alpha1.VsphereCredential{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeVsphereCredentials) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(vspherecredentialsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.VsphereCredentialList{})
	return err
}

// Patch applies the patch and returns the patched vsphereCredential.
func (c *FakeVsphereCredentials) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.VsphereCredential, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(vspherecredentialsResource, c.ns, name, pt, data, subresources...), &v1alpha1.VsphereCredential{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VsphereCredential), err
}
