/*
Copyright 2022 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen@v0.20.2. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/Mirantis/mcc-api/v2/pkg/apis/kaas/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeAzureResourceses implements AzureResourcesInterface
type FakeAzureResourceses struct {
	Fake *FakeKaasV1alpha1
	ns   string
}

var azureresourcesesResource = schema.GroupVersionResource{Group: "kaas.mirantis.com", Version: "v1alpha1", Resource: "azureresourceses"}

var azureresourcesesKind = schema.GroupVersionKind{Group: "kaas.mirantis.com", Version: "v1alpha1", Kind: "AzureResources"}

// Get takes name of the azureResources, and returns the corresponding azureResources object, and an error if there is any.
func (c *FakeAzureResourceses) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.AzureResources, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(azureresourcesesResource, c.ns, name), &v1alpha1.AzureResources{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AzureResources), err
}

// List takes label and field selectors, and returns the list of AzureResourceses that match those selectors.
func (c *FakeAzureResourceses) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.AzureResourcesList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(azureresourcesesResource, azureresourcesesKind, c.ns, opts), &v1alpha1.AzureResourcesList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.AzureResourcesList{ListMeta: obj.(*v1alpha1.AzureResourcesList).ListMeta}
	for _, item := range obj.(*v1alpha1.AzureResourcesList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested azureResourceses.
func (c *FakeAzureResourceses) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(azureresourcesesResource, c.ns, opts))

}

// Create takes the representation of a azureResources and creates it.  Returns the server's representation of the azureResources, and an error, if there is any.
func (c *FakeAzureResourceses) Create(ctx context.Context, azureResources *v1alpha1.AzureResources, opts v1.CreateOptions) (result *v1alpha1.AzureResources, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(azureresourcesesResource, c.ns, azureResources), &v1alpha1.AzureResources{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AzureResources), err
}

// Update takes the representation of a azureResources and updates it. Returns the server's representation of the azureResources, and an error, if there is any.
func (c *FakeAzureResourceses) Update(ctx context.Context, azureResources *v1alpha1.AzureResources, opts v1.UpdateOptions) (result *v1alpha1.AzureResources, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(azureresourcesesResource, c.ns, azureResources), &v1alpha1.AzureResources{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AzureResources), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeAzureResourceses) UpdateStatus(ctx context.Context, azureResources *v1alpha1.AzureResources, opts v1.UpdateOptions) (*v1alpha1.AzureResources, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(azureresourcesesResource, "status", c.ns, azureResources), &v1alpha1.AzureResources{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AzureResources), err
}

// Delete takes name of the azureResources and deletes it. Returns an error if one occurs.
func (c *FakeAzureResourceses) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(azureresourcesesResource, c.ns, name), &v1alpha1.AzureResources{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeAzureResourceses) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(azureresourcesesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.AzureResourcesList{})
	return err
}

// Patch applies the patch and returns the patched azureResources.
func (c *FakeAzureResourceses) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.AzureResources, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(azureresourcesesResource, c.ns, name, pt, data, subresources...), &v1alpha1.AzureResources{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AzureResources), err
}
