/*
Copyright 2022 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen@v0.20.2. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/Mirantis/mcc-api/v2/pkg/apis/kaas/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeAzureCredentials implements AzureCredentialInterface
type FakeAzureCredentials struct {
	Fake *FakeKaasV1alpha1
	ns   string
}

var azurecredentialsResource = schema.GroupVersionResource{Group: "kaas.mirantis.com", Version: "v1alpha1", Resource: "azurecredentials"}

var azurecredentialsKind = schema.GroupVersionKind{Group: "kaas.mirantis.com", Version: "v1alpha1", Kind: "AzureCredential"}

// Get takes name of the azureCredential, and returns the corresponding azureCredential object, and an error if there is any.
func (c *FakeAzureCredentials) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.AzureCredential, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(azurecredentialsResource, c.ns, name), &v1alpha1.AzureCredential{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AzureCredential), err
}

// List takes label and field selectors, and returns the list of AzureCredentials that match those selectors.
func (c *FakeAzureCredentials) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.AzureCredentialList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(azurecredentialsResource, azurecredentialsKind, c.ns, opts), &v1alpha1.AzureCredentialList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.AzureCredentialList{ListMeta: obj.(*v1alpha1.AzureCredentialList).ListMeta}
	for _, item := range obj.(*v1alpha1.AzureCredentialList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested azureCredentials.
func (c *FakeAzureCredentials) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(azurecredentialsResource, c.ns, opts))

}

// Create takes the representation of a azureCredential and creates it.  Returns the server's representation of the azureCredential, and an error, if there is any.
func (c *FakeAzureCredentials) Create(ctx context.Context, azureCredential *v1alpha1.AzureCredential, opts v1.CreateOptions) (result *v1alpha1.AzureCredential, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(azurecredentialsResource, c.ns, azureCredential), &v1alpha1.AzureCredential{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AzureCredential), err
}

// Update takes the representation of a azureCredential and updates it. Returns the server's representation of the azureCredential, and an error, if there is any.
func (c *FakeAzureCredentials) Update(ctx context.Context, azureCredential *v1alpha1.AzureCredential, opts v1.UpdateOptions) (result *v1alpha1.AzureCredential, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(azurecredentialsResource, c.ns, azureCredential), &v1alpha1.AzureCredential{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AzureCredential), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeAzureCredentials) UpdateStatus(ctx context.Context, azureCredential *v1alpha1.AzureCredential, opts v1.UpdateOptions) (*v1alpha1.AzureCredential, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(azurecredentialsResource, "status", c.ns, azureCredential), &v1alpha1.AzureCredential{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AzureCredential), err
}

// Delete takes name of the azureCredential and deletes it. Returns an error if one occurs.
func (c *FakeAzureCredentials) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(azurecredentialsResource, c.ns, name), &v1alpha1.AzureCredential{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeAzureCredentials) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(azurecredentialsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.AzureCredentialList{})
	return err
}

// Patch applies the patch and returns the patched azureCredential.
func (c *FakeAzureCredentials) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.AzureCredential, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(azurecredentialsResource, c.ns, name, pt, data, subresources...), &v1alpha1.AzureCredential{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AzureCredential), err
}
